// languageData.js
const languageData = [
  {
    code: 'en',
    label: 'English',
    translations: {
      englishLan: 'English',
      azerbaijaniLan: 'Azerbaijani',
      spanishLan: 'Spanish',
      germanLan: 'German',
      chineseLan: 'Chinese',
      frenchLan: 'French',
      turkishLan: 'Turkish',
      russianLan: 'Russian',
      lightTheme: 'Light',
      darkTheme: 'Dark',
      autoTheme: 'Auto',
      aboutUsItem: 'About us',
      opportunityItem: 'Career opportunities',
      activitiesItem: 'Our activities',
      blogPostItem: 'Blog Posts',
      contactItem: 'Contact us',
      exhibitions: 'Exhibitions',
      events: 'Events',
      vacancy: 'Vacancy',
      scholarshipProgram: 'Scholarship program',
      internshipProgram: 'Internship program',
      logistics: 'Logistics',
      humanResources: 'Human resources',
      finance: 'Finance',
      Events:'Events',
      submission:'Submission',
      position:'Position',
      blogs:'Blogs',
      employment:'Employment',
      support:'Support',
      menu:'Menu',
      absheronLogisticCenter:'Absheron Logistic Center',
      ourSubsidiaries:'Our subsidiaries',
      advantagesOfWorkingWithUs:'Advantages of working with us',
      news:'News',
    },
  },
  {
    code: 'tr',
    label: 'Türkçe',
    translations: {
      englishLan: 'İngilizce',
      azerbaijaniLan: 'Azerice',
      spanishLan: 'İspanyolca',
      germanLan: 'Almanca',
      chineseLan: 'Çince',
      frenchLan: 'Fransızca',
      turkishLan: 'Türkçe',
      russianLan: 'Rusça',
      lightTheme: 'Açık',
      darkTheme: 'Koyu',
      autoTheme: 'Otomatik',
    },
  },
  {
    code: 'az',
    label: 'Azərbaycanca',
    translations: {
      englishLan: 'İngilis dili',
      azerbaijaniLan: 'Azərbaycan dili',
      spanishLan: 'İspan dili',
      germanLan: 'Alman dili',
      chineseLan: 'Çin dili',
      frenchLan: 'Fransız dili',
      turkishLan: 'Türk dili',
      russianLan: 'Rus dili',
      lightTheme: 'İşıq',
      darkTheme: 'Qaranlıq',
      autoTheme: 'Avtomatik',
    },
  },
  {
    code: 'es',
    label: 'Español',
    translations: {
      englishLan: 'Inglés',
      azerbaijaniLan: 'Azerbaiyano',
      spanishLan: 'Español',
      germanLan: 'Alemán',
      chineseLan: 'Chino',
      frenchLan: 'Francés',
      turkishLan: 'Turco',
      russianLan: 'Ruso',
      lightTheme: 'Claro',
      darkTheme: 'Oscuro',
      autoTheme: 'Automático',
    },
  },
  {
    code: 'ru',
    label: 'Русский',
    translations: {
      englishLan: 'Английский',
      azerbaijaniLan: 'Азербайджанский',
      spanishLan: 'Испанский',
      germanLan: 'Немецкий',
      chineseLan: 'Китайский',
      frenchLan: 'Французский',
      turkishLan: 'Турецкий',
      russianLan: 'Русский',
      lightTheme: 'Светлая',
      darkTheme: 'Тёмная',
      autoTheme: 'Авто',
    },
  },
  {
    code: 'zh',
    label: '中文',
    translations: {
      englishLan: '英语',
      azerbaijaniLan: '阿塞拜疆语',
      spanishLan: '西班牙语',
      germanLan: '德语',
      chineseLan: '中文',
      frenchLan: '法语',
      turkishLan: '土耳其语',
      russianLan: '俄语',
      lightTheme: '浅色',
      darkTheme: '深色',
      autoTheme: '自动',
    },
  },
  {
    code: 'de',
    label: 'Deutsch',
    translations: {
      englishLan: 'Englisch',
      azerbaijaniLan: 'Aserbaidschanisch',
      spanishLan: 'Spanisch',
      chineseLan: 'Chinesisch',
      frenchLan: 'Französisch',
      germanLan: 'Deutsch',
      turkishLan: 'Türkisch',
      russianLan: 'Russisch',
      lightTheme: 'Hell',
      darkTheme: 'Dunkel',
      autoTheme: 'Automatisch',
    },
  },
  {
    code: 'fr',
    label: 'Français',
    translations: {
      englishLan: 'Anglais',
      azerbaijaniLan: 'Azéri',
      spanishLan: 'Espagnol',
      germanLan: 'Allemand',
      chineseLan: 'Chinois',
      frenchLan: 'Français',
      turkishLan: 'Turc',
      russianLan: 'Russe',
      lightTheme: 'Clair',
      darkTheme: 'Sombre',
      autoTheme: 'Automatique',
    },
  },
];

export default languageData;
